version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tautulli_web_1
      APP_PORT: 8181

  web:
    image: linuxserver/tautulli:2.14.5@sha256:ff87ded2487774cb71fee4fb96c62e815bff321b9a52e2e1404bf67f72b209ae
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000