version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: seafile
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  db:
    image: mariadb:10.11@sha256:3e8f15fd6328340f4024fcb7005cce0da1fa5065554b7c420626f803b67ddc12
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=wiufh%woi&rwioj*q
      - MYSQL_USER=seafile
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql

  memcached:
    image: memcached:1.6.18@sha256:4ab520657d9919221f752771bb013d632c9b39cea9dfae9162244b2e39885bcd
    container_name: seafile-memcached
    entrypoint: memcached -m 256

  web:
    image: seafileltd/seafile-mc:10.0.1@sha256:70628f29c6634e7d7df64b942e06b2f46990acbd5c6cd84ab907ce06e07ffdc1
    container_name: seafile
    volumes:
      - ${APP_DATA_DIR}/seafile-data:/shared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=wiufh%woi&rwioj*q
      - NON
    depends_on:
      - db
      - memcached
