#!/usr/bin/env bash
set -euo pipefail

# We're forced to run user/group 1500
# More detail here: https://github.com/invoiceninja/dockerfiles/blob/ad3ffc227d63740330f761dad6e8c87768577847/alpine/5/Dockerfile#L70-L80
# So we set the owner of the data directories to 1500:1500
APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)/data"

DESIRED_OWNER="1500:1500"

PUBLIC_DATA_DIR="${APP_DATA_DIR}/public"
STORAGE_DATA_DIR="${APP_DATA_DIR}/storage"

invoiceninja_correct_permission() {
	local -r path="${1}"

	if [[ -d "${path}" ]]; then
		owner=$(stat -c "%u:%g" "${path}")

		if [[ "${owner}" != "${DESIRED_OWNER}" ]]; then
			chown "${DESIRED_OWNER}" "${path}"
		fi
	fi
}

invoiceninja_correct_permission "${PUBLIC_DATA_DIR}"
invoiceninja_correct_permission "${STORAGE_DATA_DIR}"

# Generate and save the Laravel APP_KEY if it doesn't exist
LARAVEL_APP_KEY_FILE_PATH="${APP_DATA_DIR}/laravel-app-key.txt"
# If the file doesn't exist, we generate a new key and save it
if [[ ! -f "${LARAVEL_APP_KEY_FILE_PATH}" ]]; then
	echo "Generating Laravel APP_KEY..."
	APP_KEY="${UMBREL_ROOT}/scripts/app" compose "${APP_ID}" run --rm app php artisan key:generate --show
	echo "APP_KEY in prestart: ${APP_KEY}"
	echo "Saving Laravel APP_KEY to ${LARAVEL_APP_KEY_FILE_PATH}..."
	echo "${APP_KEY}" > "${LARAVEL_APP_KEY_FILE_PATH}"
fi
