version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mealie_frontend_1
      APP_PORT: 3000

  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5@sha256:d8ff0ecd5cfe460fb593a99fa78d9ca17401925d287c723a319abd764f80b9f7
    environment:
      - API_URL=http://mealie-api:9000
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    restart: on-failure

  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5@sha256:5031ad226b8ec4c895afdc54dab654e07980dd33391a3e8106aadb3f09b73104
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      # - BASE_URL=https://mealie.yourdomain.com
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    restart: on-failure