version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mealie_server_1
      APP_PORT: 80

  server:
    image: hkotel/mealie:api-v1.0.0beta-5@sha256:5031ad226b8ec4c895afdc54dab654e07980dd33391a3e8106aadb3f09b73104
    environment:
      PUID: 1000
      PGID: 1000

      # Default Recipe Settings
      RECIPE_PUBLIC: 'true'
      RECIPE_SHOW_NUTRITION: 'true'
      RECIPE_SHOW_ASSETS: 'true'
      RECIPE_LANDSCAPE_VIEW: 'true'
      RECIPE_DISABLE_COMMENTS: 'false'
      RECIPE_DISABLE_AMOUNT: 'false'
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    restart: on-failure