version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: back-that-mac-up_server_1
      APP_PORT: 80

  server:
    # image: ...
    build: ../../../btmu-test/backend
    restart: on-failure
    environment:
      TIME_MACHINE_DIR: "/timemachine"
      TIME_MACHINE_CONTAINER_URL: "http://timemachine:50000"
    volumes:
      # this is the entire app's data dir (could consider only mounting opt-timemachine)
      - ${APP_DATA_DIR}/data:/timemachine

  timemachine:
    image: mbentley/timemachine:smb-20231122@sha256:861560184a5c9f3b4f2a8bef4549ef4168d80c57a9de81b16bc5e6eead24ff3f
    hostname: umbrel
    entrypoint: /netcat-entrypoint/entrypoint.sh
    command: ["s6-svscan", "/etc/s6"]
    environment:
      ADVERTISED_HOSTNAME: "umbrel"
      CUSTOM_SMB_CONF: ${SMB_CONF_EXISTS}
      CUSTOM_USER: "false"
      DEBUG_LEVEL: "1"
      HIDE_SHARES: "no"
      EXTERNAL_CONF: ""
      MIMIC_MODEL: "TimeCapsule8,119"
      TM_USERNAME: "timemachine"
      TM_GROUPNAME: "timemachine"
      TM_UID: "1000"
      TM_GID: "1000"
      PASSWORD: "timemachine"
      SET_PERMISSIONS: "false"
      SHARE_NAME: "Umbrel TimeMachine"
      SMB_INHERIT_PERMISSIONS: "no"
      SMB_NFS_ACES: "no"
      SMB_METADATA: "stream"
      SMB_PORT: "445"
      SMB_VFS_OBJECTS: "acl_xattr fruit streams_xattr"
      VOLUME_SIZE_LIMIT: "0"
      WORKGROUP: "WORKGROUP"
    restart: unless-stopped
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
      # don't expose the netcat port in umbrel app
      - "50000:50000"
    volumes:
      - ${APP_DATA_DIR}/data/opt-timemachine:/opt/timemachine
      - ${APP_DATA_DIR}/data/var-lib-samba:/var/lib/samba
      - ${APP_DATA_DIR}/data/var-cache-samba:/var/cache/samba
      - ${APP_DATA_DIR}/data/run-samba:/run/samba
      # volume for custom smb.conf
      - ${APP_DATA_DIR}/data/etc-samba:/etc/samba
      # volume for custom entrypoint script
      - ${APP_DATA_DIR}/entrypoint.sh:/netcat-entrypoint/entrypoint.sh
    # ulimits:
    #   nofile:
    #     soft: 65536
    #     hard: 65536