version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tandoor-recipes_web_recipes_1
      APP_PORT: 80
      PROXY_AUTH_WHITELIST: "/api/*"

  web_recipes:
    image: vabene1111/recipes:1.4.12@sha256:cd6b2a3ff9190a972e1ff16ba9246dce57c5b5b670b9772c07a408802549947e
    environment:
      - SECRET_KEY=random-text-here
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=db_recipes
      - POSTGRES_PORT=5432
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=djangodb
    volumes:
      - ${APP_DATA_DIR}/data/staticfiles:/opt/recipes/staticfiles
      - ${APP_DATA_DIR}/data/nginx_config:/opt/recipes/nginx/conf.d
      - ${APP_DATA_DIR}/data/mediafiles:/opt/recipes/mediafiles
    restart: on-failure
    depends_on:
      - db_recipes

  db_recipes:
    image: postgres:11-alpine@sha256:45800340cfea631af4c8c3870e8d7f1ae888907e39def41a3b7608ff8f16b28c
    environment:
      # check env template
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=db_recipes
      - POSTGRES_PORT=5432
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=djangodb
    volumes:
      - ${APP_DATA_DIR}/data/postgresql:/var/lib/postgresql/data
    restart: on-failure

  nginx_recipes:
    image: nginx:mainline-alpine@sha256:2e776a66a3556f001aba13431b26e448fe8acba277bf93d2ab1a785571a46d90
    # environment:
      # check env template
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/data/nginx_config:/etc/nginx/conf.d:ro
      - ${APP_DATA_DIR}/data/staticfiles:/static:ro
      - ${APP_DATA_DIR}/data/mediafiles:/media:ro
    restart: on-failure
    depends_on:
      - web_recipes