version: "3.7"

services:
  server:
    image: homeassistant/home-assistant:2023.6.3@sha256:1dd89ec1ce8de5ea869a489d5699bd91f77058ffaa6f5484b3e81323128abd2c
    network_mode: host
    # UI at port 8083 instead of the default 8123 (see pre-start hook) to avoid clash with tallycoin-connect.
    volumes:
      - ${APP_DATA_DIR}/data:/config