version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: immich_proxy_1
      APP_PORT: 8080
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: altran1502/immich-server:v1.55.1@sha256:af321b3a1eb9922079ad456f6b696ac76e9f1fc72ecc4d17c55dabc3223365c4
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${APP_DATA_DIR}/data/upload:/usr/src/app/upload
    environment:
      NODE_ENV: production
      DB_HOSTNAME: immich_postgres_1
      DB_USERNAME: ${APP_IMMICH_DB_USERNAME}
      DB_PASSWORD: ${APP_IMMICH_DB_PASSWORD}
      DB_DATABASE_NAME: ${APP_IMMICH_DB_DATABASE_NAME}
      REDIS_HOSTNAME: immich_redis_1
      LOG_LEVEL: ${APP_IMMICH_LOG_LEVEL}
      JWT_SECRET: ${APP_SEED}
      DISABLE_REVERSE_GEOCODING: ${APP_IMMICH_DISABLE_REVERSE_GEOCODING}
      REVERSE_GEOCODING_PRECISION: ${APP_IMMICH_REVERSE_GEOCODING_PRECISION}
      PUBLIC_LOGIN_PAGE_MESSAGE: ${APP_IMMICH_PUBLIC_LOGIN_PAGE_MESSAGE}
      TYPESENSE_API_KEY: "random-text-key"
    depends_on:
      - redis
      - postgres
      - typesense
    restart: on-failure

  microservices:
    image: altran1502/immich-server:v1.55.1@sha256:af321b3a1eb9922079ad456f6b696ac76e9f1fc72ecc4d17c55dabc3223365c4
    # This service cannot run under 1000:1000
    # And because the uploads are shared
    # We'll run immich specific services as root
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${APP_DATA_DIR}/data/upload:/usr/src/app/upload
    environment:
      NODE_ENV: production
      DB_HOSTNAME: immich_postgres_1
      DB_USERNAME: ${APP_IMMICH_DB_USERNAME}
      DB_PASSWORD: ${APP_IMMICH_DB_PASSWORD}
      DB_DATABASE_NAME: ${APP_IMMICH_DB_DATABASE_NAME}
      REDIS_HOSTNAME: immich_redis_1
      LOG_LEVEL: ${APP_IMMICH_LOG_LEVEL}
      JWT_SECRET: ${APP_SEED}
      DISABLE_REVERSE_GEOCODING: ${APP_IMMICH_DISABLE_REVERSE_GEOCODING}
      REVERSE_GEOCODING_PRECISION: ${APP_IMMICH_REVERSE_GEOCODING_PRECISION}
      PUBLIC_LOGIN_PAGE_MESSAGE: ${APP_IMMICH_PUBLIC_LOGIN_PAGE_MESSAGE}
      TYPESENSE_API_KEY: "random-text-key"
    depends_on:
      - redis
      - postgres
      - typesense
    restart: on-failure

  machine-learning:
    image: altran1502/immich-machine-learning:v1.55.1@sha256:461e51ebeea082eb2c634cba0f5aa999fdabc50aa35513f3c802a7742ce1a5bb
    volumes:
      - ${APP_DATA_DIR}/data/upload:/usr/src/app/upload
    environment:
      NODE_ENV: production
      DB_HOSTNAME: immich_postgres_1
      DB_USERNAME: ${APP_IMMICH_DB_USERNAME}
      DB_PASSWORD: ${APP_IMMICH_DB_PASSWORD}
      DB_DATABASE_NAME: ${APP_IMMICH_DB_DATABASE_NAME}
      REDIS_HOSTNAME: immich_redis_1
      LOG_LEVEL: ${APP_IMMICH_LOG_LEVEL}
      JWT_SECRET: ${APP_SEED}
      DISABLE_REVERSE_GEOCODING: ${APP_IMMICH_DISABLE_REVERSE_GEOCODING}
      REVERSE_GEOCODING_PRECISION: ${APP_IMMICH_REVERSE_GEOCODING_PRECISION}
      PUBLIC_LOGIN_PAGE_MESSAGE: ${APP_IMMICH_PUBLIC_LOGIN_PAGE_MESSAGE}
    depends_on:
      - postgres
    restart: on-failure

  web:
    image: altran1502/immich-web:v1.55.1@sha256:2bae0a4c71d7d1d7a7fc7fd7c382f521c80aeedfb5860514570b3fcf9a393c86
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    environment:
      DB_HOSTNAME: immich_postgres_1
      DB_USERNAME: ${APP_IMMICH_DB_USERNAME}
      DB_PASSWORD: ${APP_IMMICH_DB_PASSWORD}
      DB_DATABASE_NAME: ${APP_IMMICH_DB_DATABASE_NAME}
      REDIS_HOSTNAME: immich_redis_1
      LOG_LEVEL: ${APP_IMMICH_LOG_LEVEL}
      JWT_SECRET: ${APP_SEED}
      DISABLE_REVERSE_GEOCODING: ${APP_IMMICH_DISABLE_REVERSE_GEOCODING}
      REVERSE_GEOCODING_PRECISION: ${APP_IMMICH_REVERSE_GEOCODING_PRECISION}
      PUBLIC_LOGIN_PAGE_MESSAGE: ${APP_IMMICH_PUBLIC_LOGIN_PAGE_MESSAGE}
      IMMICH_SERVER_URL: "http://immich_server_1:3001"
      PUBLIC_IMMICH_SERVER_URL: "http://immich_server_1:3001"
    restart: on-failure

  typesense:
    image: typesense/typesense:0.24.0@sha256:3cc1251f09ef6c75a5b1f2751c04e7265c770c0f2b69cba1f9a9f20da57cfa28
    environment:
      TYPESENSE_API_KEY: "random-text-key"
      TYPESENSE_DATA_DIR: "/data"
    volumes:
      - ${APP_DATA_DIR}/data/tsdata:/data
    restart: on-failure

  proxy:
    image: altran1502/immich-proxy:v1.55.1@sha256:4e6e3fa041c40002adeffdbbd24dbf259a399fe71cd61a5d269a07fbc3dee16c
    environment:
      IMMICH_WEB_URL: "http://immich_web_1:3000"
      IMMICH_SERVER_URL: "http://immich_server_1:3001"
    depends_on:
      - server
    restart: on-failure

  redis:
    image: redis:6.2-bullseye@sha256:ffd3d04c8f7832ccdda89616ebaf3cb38414b645ebbf76dbef1fc9c36a72a2d1
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data

  postgres:
    image: postgres:14-bullseye@sha256:135c62a8134dcef829a1e4f5568bfae44bcfa2c75659ff948f43c71964366aa4
    user: "1000:1000"
    environment:
      POSTGRES_USER: ${APP_IMMICH_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_IMMICH_DB_PASSWORD}
      POSTGRES_DB: ${APP_IMMICH_DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    restart: on-failure
