version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: immich_proxy_1
      APP_PORT: 8080
      PROXY_AUTH_WHITELIST: "/api/*,/search/*"

  server:
    image: altran1502/immich-server:v1.59.1@sha256:0f611b58423ae6f544da506ff55683b0f947856a0f0bd85db0e8e48aa2837347
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${APP_DATA_DIR}/data/upload:/usr/src/app/upload
    environment:
      <<: *env
    depends_on:
      - redis
      - postgres
      - typesense
    restart: on-failure

  microservices:
    image: altran1502/immich-server:v1.59.1@sha256:0f611b58423ae6f544da506ff55683b0f947856a0f0bd85db0e8e48aa2837347
    # This service cannot run under 1000:1000
    # And because the uploads are shared
    # We'll run immich specific services as root
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${APP_DATA_DIR}/data/upload:/usr/src/app/upload
    environment:
      <<: *env
    depends_on:
      - redis
      - postgres
      - typesense
    restart: on-failure

  machine-learning:
    image: altran1502/immich-machine-learning:v1.59.1@sha256:0b16898ac1572d154673fb242e0727d0d1c82cba5948c0f1882c0ee7f56f94f2
    volumes:
      - ${APP_DATA_DIR}/data/upload:/usr/src/app/upload
      - ${APP_DATA_DIR}/data/model-cache:/cache
    environment:
      <<: *env
    depends_on:
      - postgres
    restart: on-failure

  web:
    image: altran1502/immich-web:v1.59.1@sha256:f7d58ca0d8725ede4ceb67a640336b8189381878377d150065acffc94dbfb5c9
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    environment:
      <<: *env
    restart: on-failure

  typesense:
    image: typesense/typesense:0.24.0@sha256:3cc1251f09ef6c75a5b1f2751c04e7265c770c0f2b69cba1f9a9f20da57cfa28
    environment:
      TYPESENSE_API_KEY: "any-text-for-self-hosted-typesense"
      TYPESENSE_DATA_DIR: "/data"
    volumes:
      - ${APP_DATA_DIR}/data/tsdata:/data
    restart: on-failure

  proxy:
    image: altran1502/immich-proxy:v1.59.1@sha256:5e1b1b35cb8f63a9af896790871387703b1c0c8d9b308ab1290b8e615f0f84d2
    environment:
      IMMICH_WEB_URL: "http://immich_web_1:3000"
      IMMICH_SERVER_URL: "http://immich_server_1:3001"
    depends_on:
      - server
    restart: on-failure

  redis:
    image: redis:6.2-bullseye@sha256:ffd3d04c8f7832ccdda89616ebaf3cb38414b645ebbf76dbef1fc9c36a72a2d1
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data

  postgres:
    image: postgres:14-bullseye@sha256:135c62a8134dcef829a1e4f5568bfae44bcfa2c75659ff948f43c71964366aa4
    user: "1000:1000"
    environment:
      <<: *env
      POSTGRES_USER: ${APP_IMMICH_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_IMMICH_DB_PASSWORD}
      POSTGRES_DB: ${APP_IMMICH_DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    restart: on-failure

x-environment: &env
  NODE_ENV: production
  DB_HOSTNAME: immich_postgres_1
  DB_USERNAME: immich
  DB_PASSWORD: moneyprintergobrrr
  DB_DATABASE_NAME: immich
  REDIS_HOSTNAME: immich_redis_1
  LOG_LEVEL: simple
  JWT_SECRET: ${APP_SEED}
  DISABLE_REVERSE_GEOCODING: false
  REVERSE_GEOCODING_PRECISION: 3
  PUBLIC_LOGIN_PAGE_MESSAGE: ""
  TYPESENSE_API_KEY: any-text-for-self-hosted-typesense
  IMMICH_MACHINE_LEARNING_URL: "http://immich_machine-learning_1:3003"
  PUBLIC_IMMICH_SERVER_URL: "http://immich_server_1:3001"
  IMMICH_SERVER_URL: "http://immich_server_1:3001"