version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: calibre-web_server_1
      APP_PORT: 8080

  server:
    image: lscr.io/linuxserver/calibre:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    # ports:
    #   - 8080:8080
    #   - 8181:8181
    #   - 8081:8081
    restart: on-failure