version: '3.7'

services:
  dind:
    image: docker:dind
    privileged: true
    command: dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --tls=false
    network_mode: host
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:2.18.4@sha256:94c3056dbe879f3a3df06b427713392a0962924914f5c2fc557de3797f59f926
    command: -H tcp://${DOCKER_HOST_IP}:2375
    ports:
      - "9000:9000"
    restart: unless-stopped
    depends_on:
      - dind