version: '3.7'

services:
  dind:
    image: docker:dind
    privileged: true
    # command: dockerd -H tcp://0.0.0.0:2375
    command: dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock
    network_mode: host

  portainer:
    image: portainer/portainer-ce:2.18.4@sha256:94c3056dbe879f3a3df06b427713392a0962924914f5c2fc557de3797f59f926
    # command: -H tcp://host.docker.internal:2375
    # command: -H tcp://localhost:2375
    command: -H tcp://umbrel-2.local:2375
    network_mode: host
    #ports:
    #  - "9000:9000"
    depends_on:
      - dind
    restart: unless-stopped