version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: nitter_web_1
      APP_PORT: 8080
      # APP_PROXY_AUTH: "false"
      PROXY_AUTH_WHITELIST: "/search"

  web:
    # Official Nim image used as base image for nitter doesn't offer Arm variant so using a custom image w/ patch for umbrel
    # https://github.com/ceramicwhite/nitter/tree/master/.github/workflows/dockerfile
    image: ceramicwhite/nitter:build-38985af@sha256:b81f61f1527000d27daf5f222ea27122fee7bb489900587e732e252a5654c002
    restart: on-failure
    stop_grace_period: 1m
    init: true
    user: 1000:1000
    environment:
      REDIS_HOST: "nitter_redis_1"
      REDIS_PASS: "moneyprintergobrrr"
      NITTER_THEME: '"auto_(twitter)"'
    volumes:
      - ${APP_DATA_DIR}/data/nitter:/data
    depends_on:
      - redis
  
  redis:
    image: redis:6.2.2-buster@sha256:e10f55f92478715698a2cef97c2bbdc48df2a05081edd884938903aa60df6396
    restart: on-failure
    stop_grace_period: 1m
    user: 1000:1000
    command: "redis-server --save 60 1 --loglevel warning --requirepass moneyprintergobrrr"
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data