name: Validate Compose and Manifest Files

on:
  pull_request:
    paths:
      - "**/docker-compose.yml"
      - "**/umbrel-app.yml"

jobs:
  validate_changes:
    name: Validate Changed Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get List of Changed Files
      id: changed_files
      uses: Ana06/get-changed-files@v2.2.0

    - name: Validate Changed Files
      id: validation
      run: |
        function validate_multi_architecture() {
            grep 'image:' $1 | while read -r line ; do
                IMAGE=$(echo $line | cut -d' ' -f2)
                ARCHITECTURES=$(docker run --rm mplatform/mquery:v0.5.0@sha256:d0989420b6f0d2b929fd9355f15c767f62d0e9a72cdf999d1eb16e6073782c71 $IMAGE | grep -E 'linux/amd64|linux/arm64')
                if [[ ! $ARCHITECTURES =~ "linux/amd64" ]] || [[ ! $ARCHITECTURES =~ "linux/arm" ]]; then
                  echo "::error::Image $IMAGE does not support both linux/amd64 and linux/arm architectures"
                fi
            done
        }

        function validate_version_tags() {
            if grep -q ':latest' $1 ; then
                echo "::error::Some images use the latest tag in $1"
            fi
        }

        function validate_proxy_auth() {
            if grep -q 'PROXY_AUTH_ADD: "true"' $1 ; then
                echo "::error::PROXY_AUTH_ADD is set to true in $1"
            fi
        }

        function validate_docker_compose() {
            validate_multi_architecture $1
            validate_version_tags $1
            validate_proxy_auth $1
        }

        function validate_required_fields() {
            REQUIRED_FIELDS=("manifestVersion" "id" "category" "name" "version" "tagline" "description" "developer" "website" "dependencies" "support" "port" "gallery")
            for FIELD in "${REQUIRED_FIELDS[@]}"; do
                if ! grep -q "^$FIELD:" $1 ; then
                    echo "::error::Required field $FIELD is missing from $1"
                fi
            done
        }

        function validate_category_field() {
            CATEGORY=$(grep 'category:' $1 | cut -d':' -f2 | tr -d '[:space:]')
            if [[ $CATEGORY != $(echo "$CATEGORY" | tr '[:upper:]' '[:lower:]') ]]; then
                echo "::error::Category value in $1 is not lowercase"
            fi
        }

        function validate_optional_fields() {
            OPTIONAL_FIELDS=("submission" "submitter" "defaultPassword" "defaultUsername" "repo")
            for FIELD in "${OPTIONAL_FIELDS[@]}"; do
                if ! grep -q "$FIELD:" $1 ; then
                    echo "::warning::$FIELD is an optional field and is missing from $1"
                fi
            done
        }

        function validate_umbrel_app() {
            validate_required_fields $1
            validate_category_field $1
            validate_optional_fields $1
        }

        for file in ${{ steps.changed_files.outputs.all }}; do
            case "$file" in
                *docker-compose.yml)
                    validate_docker_compose "$file"
                    ;;
                *umbrel-app.yml)
                    validate_umbrel_app "$file"
                    ;;
            esac
        done
      shell: bash

    - name: Post Validation Feedback on PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          🤖 **Validation Report**:

          The latest changes to this pull request have been checked. Here's the current validation status:

          ### Docker Compose Validations (`docker-compose.yml`)
          - ${{ steps.validation.outputs.IMAGE_ERROR != '' && '🛑' || '✅' }} Multi-Architecture Images: ${{ steps.validation.outputs.IMAGE_ERROR }}
          - ${{ steps.validation.outputs.LATEST_TAG_ERROR != '' && '🛑' || '✅' }} Versioned Images: ${{ steps.validation.outputs.LATEST_TAG_ERROR }}
          - ${{ steps.validation.outputs.PROXY_AUTH_ERROR != '' && '🛑' || '✅' }} Proxy Auth Configuration: ${{ steps.validation.outputs.PROXY_AUTH_ERROR }}

          ### Umbrel App Validations (`umbrel-app.yml`)
          - ${{ steps.validation.outputs.REQUIRED_FIELD_ERROR != '' && '🛑' || '✅' }} Required Fields: ${{ steps.validation.outputs.REQUIRED_FIELD_ERROR }}
          - ${{ steps.validation.outputs.OPTIONAL_FIELD_WARNING != '' && '⚠️' || '✅' }} Optional Fields: ${{ steps.validation.outputs.OPTIONAL_FIELD_WARNING }}
          - ${{ steps.validation.outputs.CATEGORY_ERROR != '' && '🛑' || '✅' }} Category Field: ${{ steps.validation.outputs.CATEGORY_ERROR }}

          Please review any items marked with 🛑 or ⚠️ and make necessary corrections. If you have questions or need assistance, feel free to ask!
